<div id="messages_product_view"><?php echo $this->getMessagesBlock()->toHtml() ?></div>

<header>
    <div id="banner">
        <?php if(count( $this->getStores() )>1): ?>
            <div class="alignRight">
                <div class="form-language">
                    <label for="select-language"><?php echo $this->__('Language:') ?></label>
                    <select id="select-language" title="<?php echo $this->__('Language') ?>" onchange="window.location.href=this.value">
                        <?php foreach ($this->getStores() as $_lang): ?>
                            <?php $_selected = ($_lang->getId() == $this->getCurrentStoreId()) ? ' selected="selected"' : '' ?>
                            <option value="<?php echo $_lang->getCurrentUrl() ?>"<?php echo $_selected ?>><?php echo $this->escapeHtml($_lang->getName()) ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>
        <?php endif; ?>

        <div class="banner-title alignCenter">
            <div class="inlineBlock alignLeft">
                <p>我是劉力誠<br>Liu Li-Cheng</p>
                <h1>網頁程式設計師</h1>
                <p>Web Developer</p>
            </div>
        </div>
    </div>
    <nav class="main-nav">
        <ul>
            <li><a href="#service">我的服務<br>Services</a></li>
            <li><a href="#idx-portfolio">作品集<br>Portfolio</a></li>
            <li><a href="#about">關於我<br>About me</a></li>
            <li><a href="#contact">與我連絡<br>Contact me</a></li>
        </ul>
    </nav>
</header>

<!--$this->getFormAction() => setFormAction( Mage::getUrl('*/*/post') );-->
<form action="<?php echo $this->getFormAction(); ?>" id="block_aboutme" method="post" class="scaffold-form">
    <div class="fieldset">
        <h2 class="legend"><?php echo Mage::helper('contacts')->__('Contact Information') ?></h2>
        <p class="required"><?php echo Mage::helper('contacts')->__('* Required Fields') ?></p>
        <ul class="form-list">
            <li class="fields">
                <div class="field">
                    <label for="name" class="required"><em>*</em><?php echo Mage::helper('contacts')->__('Name') ?></label>
                    <div class="input-box">
                        <input name="name" id="name" title="<?php echo Mage::helper('contacts')->__('Name') ?>" value="<?php echo $this->escapeHtml($this->helper('contacts')->getUserName()) ?>" class="input-text required-entry" type="text" />
                    </div>
                </div>
                <div class="field">
                    <label for="email" class="required"><em>*</em><?php echo Mage::helper('contacts')->__('Email') ?></label>
                    <div class="input-box">
                        <input name="email" id="email" title="<?php echo Mage::helper('contacts')->__('Email') ?>" value="<?php echo $this->escapeHtml($this->helper('contacts')->getUserEmail()) ?>" class="input-text required-entry validate-email" type="email" autocapitalize="off" autocorrect="off" spellcheck="false" />
                    </div>
                </div>
            </li>
            <li class="wide">
                <label for="message" class="required"><em>*</em><?php echo Mage::helper('aboutme')->__('Message') ?></label>
                <div class="input-box">
                    <textarea name="message" id="message" title="<?php echo Mage::helper('aboutme')->__('Message') ?>" class="required-entry input-text" cols="5" rows="3"></textarea>
                </div>
            </li>
        </ul>
    </div>
    <div class="buttons-set">
        <input type="text" name="hideit" id="hideit" value="" style="display:none !important;" />
        <button type="submit" title="<?php echo Mage::helper('aboutme')->__('Submit') ?>" class="button"><span><?php echo Mage::helper('aboutme')->__('Submit') ?></span></button>
    </div>

    <div class="pageToTop displayNone">
        <i class="fa fa-arrow-circle-o-up fa-4x goldenrod"></i>
    </div>

</form>

<script type="text/javascript">
    /*to enable the javascript validation, pass the form id into the class*/
    //< ![CDATA[
    var aboutus = new VarienForm('block_aboutme');
    //]]>
</script>

<!-- Pixedelic Camera -->
<div style="width: 90%;margin: 0 auto;">
    <div class="camera_wrap">
        <!--        <div data-src="--><?php //echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'aboutme/'; ?><!--img/002.jpg" data-thumb="--><?php //echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'aboutme/'; ?><!--img/thumb-002.jpg" data-link="#"></div>-->
        <!--        <div data-src="--><?php //echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'aboutme/'; ?><!--img/003.jpg" data-thumb="--><?php //echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'aboutme/'; ?><!--img/thumb-003.jpg" data-link="#"></div>-->
        <!--        <div data-src="--><?php //echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'aboutme/'; ?><!--img/004.jpg" data-thumb="--><?php //echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'aboutme/'; ?><!--img/thumb-004.jpg" data-link="#"></div>-->
        <div data-src="http://www.taiwan-motors.com.tw/lic/images/a1-test.jpg" data-thumb="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'aboutme/'; ?>img/thumb-004.jpg" data-link="#"></div>
        <div data-src="http://www.taiwan-motors.com.tw/lic/images/a1-test.jpg" data-thumb="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'aboutme/'; ?>img/thumb-004.jpg" data-link="#"></div>
        <div data-src="http://www.taiwan-motors.com.tw/lic/images/a1-test.jpg" data-thumb="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'aboutme/'; ?>img/thumb-004.jpg" data-link="#"></div>
    </div>
</div>

<script>
    jQuery('.camera_wrap').camera({
        alignment: 'center',
        fx: 'scrollLeft',
        hover: true,
        navigation: false,
        navigationHover: true,
        pagination: false,
        portrait: true,
        thumbnails: true,
        time: 3000
    });

    function updateMaxHeight () {
        var elementToUpdateMaxHeight = ["div#banner"];
        elementToUpdateMaxHeight.each(function (element) {
            jQuery(element).css({
                "max-height": jQuery(window).height()
            });
        });
    }

    function scrollToTop () {
        jQuery('.pageToTop').click(function () {
            jQuery("html, body").animate({scrollTop:0}, 500, 'swing');
        });

        jQuery(window).scroll(function (event) {
            if (jQuery(window).scrollTop() > 10) {
                console.log(jQuery(window).scrollTop(), 'more than 10, display');
                jQuery('.pageToTop').show();
            } else {
                console.log(jQuery(window).scrollTop(), 'hide');
                jQuery('.pageToTop').hide();
            }
        });
    }

    jQuery(document).ready(function () {
        updateMaxHeight();
        //If the User resizes the window, adjust the #container height
        jQuery(window).on("resize", updateMaxHeight);
        scrollToTop();
    });
</script>



