<div>
    <script type="text/javascript">// <![CDATA[
        jQuery(function(){
            jQuery('#camera_wrap').camera({
                alignmen: 'topCenter',
                height: '78.125%',
                minHeight: '400px',
                loader : false,
                navigation: false,
                fx: 'simpleFade',
                navigationHover:false,
                thumbnails: true,
                playPause: false,
                pagination:false,
            });
        });
        // ]]></script>
</div>
<div class="slider-block">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
                <div class="fluid_container_wrap">
                    <div class="fluid_container">
                        <div id="camera_wrap" class="camera_wrap camera_orange_skin">
                            <div data-link="http://www.rosewill.com/index.php/rwAdMin/cms_wysiwyg/directive/___directive/e3tzdG9yZSB1cmw9Jyd9fQ,,/key/907f157cecc3314f28526229a8d3d1707d0264a63275fa30363491dad54716f0/home-renovation.html" data-thumb="http://www.rosewill.com/index.php/rwAdMin/cms_wysiwyg/directive/___directive/e3tza2luIHVybD0naW1hZ2VzL2NhbWVyYS90aHVtYnMvR2FtaW5nX2NvbXB1dGVyY2FzZV9ncmV5X3RodW1iXzI4MHgxNjAuanBnJ319/key/907f157cecc3314f28526229a8d3d1707d0264a63275fa30363491dad54716f0/" data-src="http://www.rosewill.com/index.php/rwAdMin/cms_wysiwyg/directive/___directive/e3tza2luIHVybD0naW1hZ2VzL2NhbWVyYS9zbGlkZXMvR2FtaW5nX2NvbXB1dGVyY2FzZV9ncmV5X2Jhbm5lcl84NjB4NDgwLmpwZyd9fQ,,/key/907f157cecc3314f28526229a8d3d1707d0264a63275fa30363491dad54716f0/">
                                <div class="camera_caption fadeFromLeft">
                                    <div class="lof_camera_title">Explosive Gear for Your Arsenal</div>
                                    <p>Powerful Peripherals. Winning Gear.</p>
                                </div>
                            </div>
                            <div data-link="http://www.rosewill.com/index.php/rwAdMin/cms_wysiwyg/directive/___directive/e3tzdG9yZSB1cmw9Jyd9fQ,,/key/907f157cecc3314f28526229a8d3d1707d0264a63275fa30363491dad54716f0/house-cleaning.html" data-thumb="http://www.rosewill.com/index.php/rwAdMin/cms_wysiwyg/directive/___directive/e3tza2luIHVybD0naW1hZ2VzL2NhbWVyYS90aHVtYnMvSG9tZV9JY2VtYWtlcl9ncmV5X3RodW1iXzI4MHgxNjAuanBnJ319/key/907f157cecc3314f28526229a8d3d1707d0264a63275fa30363491dad54716f0/" data-src="http://www.rosewill.com/index.php/rwAdMin/cms_wysiwyg/directive/___directive/e3tza2luIHVybD0naW1hZ2VzL2NhbWVyYS9zbGlkZXMvSG9tZV9JY2VtYWtlcl9ncmV5X2Jhbm5lcl84NjB4NDgwLmpwZyd9fQ,,/key/907f157cecc3314f28526229a8d3d1707d0264a63275fa30363491dad54716f0/">
                                <div class="camera_caption fadeFromLeft">
                                    <div class="lof_camera_title">Rosewill Connects You to the 21st Century</div>
                                    <p>Keep Your Systems Running at Their Best</p>
                                </div>
                            </div>
                            <div data-link="http://www.rosewill.com/index.php/rwAdMin/cms_wysiwyg/directive/___directive/e3tzdG9yZSB1cmw9Jyd9fQ,,/key/907f157cecc3314f28526229a8d3d1707d0264a63275fa30363491dad54716f0/heating-cooling.html" data-thumb="http://www.rosewill.com/index.php/rwAdMin/cms_wysiwyg/directive/___directive/e3tza2luIHVybD0naW1hZ2VzL2NhbWVyYS90aHVtYnMvSVRfYmFja3BhY2tfZ3JleV90aHVtYl8yODB4MTYwLmpwZyd9fQ,,/key/907f157cecc3314f28526229a8d3d1707d0264a63275fa30363491dad54716f0/" data-src="http://www.rosewill.com/index.php/rwAdMin/cms_wysiwyg/directive/___directive/e3tza2luIHVybD0naW1hZ2VzL2NhbWVyYS9zbGlkZXMvSVRfYmFja3BhY2tfZ3JleV9iYW5uZXJfODYweDQ4MC5qcGcnfX0,/key/907f157cecc3314f28526229a8d3d1707d0264a63275fa30363491dad54716f0/">
                                <div class="camera_caption fadeFromLeft">
                                    <div class="lof_camera_title">Innovations for Life's Simple Pleasures</div>
                                    <p>Life is a Little Easier with Rosewill</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">&nbsp;</div>
            </div>
        </div>
    </div>
</div>