
<?php $_htmlId      = $this->getElement()->getHtmlId() ?>

<tr>
    <td>
        <table cellspacing="0" class="data border" id="channel_name_table">
            <thead>
            <tr class="headings">
                <th><?php echo Mage::helper('catalog')->__('Customer Group') ?></th>
                <th><?php echo Mage::helper('catalog')->__('Qty') ?></th>
            </tr>
            </thead>
            <tbody id="<?php echo $_htmlId ?>_container">

            </tbody>
            <tfoot>
            <tr>
                <td <?php if (!$_showWebsite): ?>style="display:none"<?php endif; ?>></td>
                <td colspan="4" class="a-right"><?php echo $this->getAddButtonHtml() ?></td>
            </tr>
            </tfoot>
        </table>

    </td>
</tr>


<script type="text/javascript">
    var channelNameRowTemplate = '<tr>'
        + '</tr>';

    var channelNameControl = {
        template: new Template(tierPriceRowTemplate, new RegExp('(^|.|\\r|\\n)({{\\s*(\\w+)\\s*}})', "")),
        itemsCount: 0,
        addItem : function () {
        },
        disableElement: function(el) {
            el.disabled = true;
            el.addClassName('disabled');
        },
        deleteItem: function(event) {
            var tr = Event.findElement(event, 'tr');
            if (tr) {
                Element.select(tr, '.delete').each(function(elem){elem.value='1'});
                Element.select(tr, ['input', 'select']).each(function(elem){elem.hide()});
                Element.hide(tr);
                Element.addClassName(tr, 'no-display template');
            }
            return false;
        }
    };
</script>